- name: drop all ICMP requests and other traffic
  ansible.posix.firewalld:
    zone: public
    state: enabled
    permanent: true
    target: DROP
  notify: reload firewalld

- name: permit SSH traffic for public zone
  ansible.posix.firewalld:
    service: ssh
    zone: public
    permanent: true
    state: enabled
  notify: reload firewalld

- name: permit HTTPS requests to the webserver
  ansible.posix.firewalld:
    service: http
    zone: public
    permanent: true
    state: enabled
  notify: reload firewalld

- name: permit tcp traffic on port 8388 for shadowsocks
  ansible.posix.firewalld:
    rich_rule: rule family=ipv4 port port=8388 protocol=tcp accept
    zone: public
    permanent: true
    immediate: true
    state: enabled
  notify: reload firewalld


