---
- name: Install and run Lynis audit on target systems
  hosts: all
  order: sorted
  become_method: sudo
  become_user: root
  become: true

  vars:
    required_packages_debian:
      - lynis

  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        pkg: "{{ required_packages_debian }}"
        update_cache: true
        state: present
      when: (ansible_os_family == "Debian") or (ansible_os_family == "Ubuntu")

    - name: Copy Lynis default configuration
      ansible.builtin.template:
        src: files/Lynis/default.prf.j2
        dest: /etc/lynis/default.prf
        owner: root
        group: root
        mode: 0644

    - name: Run Lynis system audit
      ansible.builtin.shell:
        cmd: "lynis audit system --no-colors --cronjob --no-log --verbose > /root/lynis_audit.log"
        creates: "/root/lynis_audit_raw.log"

    - name: Check if Lynis report exists
      ansible.builtin.stat:
        path: "/root/lynis_audit.log"
      register: report