- name: Copy php.ini
  ansible.builtin.copy:
    src: php/8.1/fpm/php.ini
    dest: /etc/php/8.1/fpm/php.ini
    owner: root
    group: root
    mode: '0644'

- name: Start php-fpm service
  ansible.builtin.service:
    name: php8.1-fpm
    state: started
    enabled: true
