- name: Copy task file
  ansible.builtin.copy:
    src: files/rkhunter
    dest: /etc/default/rkhunter
    mode: '0644'
    owner: root
    group: root

- name: Copy config file
  ansible.builtin.copy:
    src: files/rkhunter.conf
    dest: /etc/rkhunter.conf
    mode: '0644'
    owner: root
    group: root

- name: Update rkhunter database
  ansible.builtin.command: /usr/bin/rkhunter --update
  register: result
  failed_when:
    - result.rc == 1
  notify: update rkhunter
