- name: Install required packages
  ansible.builtin.apt:
    pkg: 
      - apparmor
      - apparmor-notify
      - apparmor-utils
      - apparmor-profiles
      - apparmor-profiles-extra
      - libapache2-mod-apparmor
    state: present
  
- name: apache profile tasks
  ansible.builtin.import_tasks: apache_profile.yml

- name: sshd profile tasks
  ansible.builtin.import_tasks: sshd_profile.yml
