- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - apache2
      - php8.1
      - php8.1-fpm
      - libapache2-mod-apparmor
      - php-xml
      - php-mbstring
    state: present

- name: Purge conflicting packages
  ansible.builtin.apt:
    pkg:
      - libapache2-mod-php8.1
      - php-fpm
    state: absent
    purge: true

- name: Include php tasks
  ansible.builtin.import_tasks: php.yml

- name: Include apache2 tasks
  ansible.builtin.import_tasks: apache2.yml

- name: Include application tasks
  ansible.builtin.import_tasks: application.yml
