- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - apparmor
      - apparmor-notify
      - apparmor-utils
      - apparmor-profiles
      - apparmor-profiles-extra
      - libapache2-mod-apparmor
    state: present

# apache profile buggy with php-fpm, dunno...
- name: Apache profile tasks
  ansible.builtin.import_tasks: apache_profile.yml
  notify: reload apparmor

- name: Sshd profile tasks
  ansible.builtin.import_tasks: sshd_profile.yml
  notify: reload apparmor

- name: PHP-FPM profile tasks
  ansible.builtin.import_tasks: php8.1-fpm_profile.yml
  notify: reload apparmor

