# Copy sshd profile
- name: Copy sshd apparmor profile
  ansible.builtin.copy:
    src: /usr/share/apparmor/extra-profiles/usr.sbin.sshd
    remote_src: true
    dest: /etc/apparmor.d/usr.sbin.sshd
    mode: '0644'
    owner: root
    group: root

- name: Enforce sshd aa profile
  ansible.builtin.command:
    cmd: aa-enforce /etc/apparmor.d/usr.sbin.sshd

- name: Reload sshd aa profile
  ansible.builtin.command:
    cmd: apparmor_parser -r /etc/apparmor.d/usr.sbin.sshd
  notify: restart sshd